### ISSUE TITLE
Use datasources instead of dependsOn

### ISSUE THREAD

**Issue by akum32** [MYOB-Technology/kumo-plugins#7]
Instead of a module directly depending on another module for outputs, we should introduce the concept of data sources (similar to terraform). This will enable looser coupling between modules and help support scenarios where modules may be in separate repositories, or use a different deployment mechanism or don't store their outputs in buckets.

Instead of `deployment-settings.js` having
```
dependsOn: [
    'moduleA/ops',
    'moduleB/ops'
]
```
You could replace with:
```
dataSources: {
    'moduleAOutputs': {
        provider: 's3-bucket',
        bucket: 'module-outputs'
        .....
    }
    'moduleBOutputs': {
        provider: 'script',
        cmd: 'cat some-json-file'
    }
}
```

Different data source providers could be implemented to support different data origins and each data source would need to make the data available in JSON compatible format. Then each data source could be fetched / evaluated prior to execution of `tasks` and made available via a built-in json schema ref `#/_dataSources/<dataSourceName>`:

```
tasks: [
        {
            id: 'some-task',
            run: {
               script: 'aws s3 cp some-file $BUCKET',
               envVars: {
                   BUCKET: {$ref: '#/_dataSources/moduleAOutputs/bucket'}
               }
            }
        }
]
```

All data from data sources could also be made available via a built in environment variable `$KUMO_DATA_SOURCE_DATA` which could be used in the `tasks` section. The value of this env variable would be the combined json of all data sources keyed by the data source name. e.g.

```
{
    'moduleAOutputs': {...},
    'moduleBOutputs': {....}
}
```

And it could be used in tasks:
```
tasks: [
        {
            id: 'some-task',
            run: {
               script: '...some script... $KUMO_DATA_SOURCE_DATA'
            }
        }
]
```

Note: Once data sources are implemented, `dependsOn` should be removed and issue #8 should be fixed.

**Comment by ryu1kn** [comment]
Current `dependsOn` doesn't work on the below case:

* Module B wants to use the output of module A
* Module B needs to be deployed per environment, whereas A is needed only 1 across all environments

Specifying that "B depends on A" does not work as the deployer looks for A's output for the environment B is going to be deployed to, which does not exist.

**Comment by ryu1kn** [comment]
From module B, we cannot get `outputsBucket` of module A; so there's no way to get A's output from module B, is it?
